### PR TITLE
Nicholas/m vto v bug

### LINKED ISSUE #158: Low and Avg cell voltage is labelled with wrong units
In display mode, units are labelled with V instead of mV

### PR DESCRIPTION
**Pull request by nicholasc120**
fixes #158

### CODE REVIEW

File: src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp [hunk 1]
```diff
@@ -24,7 +24,7 @@ namespace
     const QString REQUESTED_FAN_ON = "background-color: rgb(64, 161, 191);";
     const QString FAN_OFF = "background-color: grey;";
 
-    const int MV_TO_V = 1000;
+    const float MV_TO_V = 1000;
```
Comment (bill-luu) [inline src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp]: Did this need to be changed?

File: src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp [hunk 2]
```diff
@@ -454,6 +454,7 @@ void BatteryView::requestedFanSpeedReceived(int requestedFanSpeed)
 
 void BatteryView::lowCellVoltageReceived(float lowCellVoltage)
 {
+
```
Comment (bill-luu) [inline src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp]: I think you can remove this new line

File: src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp (hunk 1 above)
Comment (nicholasc120) [reply src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp]: Yes, an int * float in Qt is an int.

Comment (nicholasc120) [reply src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp]: > What changed on the UI file?

The Race mode dashboard had to be reorganized slightly since the conversion from mV to V made some decimal numbers that would get cut off as text.
