### PR TITLE
Mob/fan speed fix

### LINKED ISSUE #147: 2nd Square for the Fan Speed and Requested Fan Speed Do Not Change Color
The 2nd (1st if zero-indexed) square for the fan speed and requested fan speed does not turn blue or orange in debug mode. This occurs when the inital fan speed/requested speed is 0 and is then set to a number higher than 2.
image
If the first set of data for the Fan Speed/Requested speed is higher than 5, it works properly
image

### PR DESCRIPTION
**Pull request by bill-luu**
fixes #147

### CODE REVIEW

File: src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp [hunk 1]
```diff
@@ -306,149 +320,33 @@ void BatteryView::fanSpeedReceived(int fanSpeed)
...
     {
-        ui_.requestedSpeed1().setStyleSheet(REQUESTED_FAN_ON);
-        ui_.requestedSpeed1().setStyleSheet(REQUESTED_FAN_ON);
-        ui_.requestedSpeed3().setStyleSheet(REQUESTED_FAN_ON);
-        ui_.requestedSpeed4().setStyleSheet(REQUESTED_FAN_ON);
-        ui_.requestedSpeed5().setStyleSheet(REQUESTED_FAN_ON);
-        ui_.requestedSpeed6().setStyleSheet(REQUESTED_FAN_ON);
+        if (i < requestedFanSpeed)
+        {
+            requestedFanSpeedList_[i]->setStyleSheet(FAN_ON);
```
Comment (mglyngberg) [inline src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp]: This should set the stylesheet to REQUESTED_FAN_ON instead of FAN_ON
